apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pv-claim
spec:
  storageClassName: ibmc-file-gold 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

